TYPE=VIEW
query=select `info_colaboradores`.`datos_generales`.`cif` AS `cif`,`info_colaboradores`.`datos_generales`.`sexo` AS `sexo`,`info_colaboradores`.`datos_generales`.`estado_civil` AS `estado_civil`,`info_colaboradores`.`datos_generales`.`nit` AS `nit`,`info_colaboradores`.`datos_generales`.`nacionalidad` AS `nacionalidad`,`info_colaboradores`.`datos_generales`.`primer_nombre` AS `primer_nombre`,`info_colaboradores`.`datos_generales`.`segundo_nombre` AS `segundo_nombre`,`info_colaboradores`.`datos_generales`.`tercer_nombre` AS `tercer_nombre`,`info_colaboradores`.`datos_generales`.`primer_apellido` AS `primer_apellido`,`info_colaboradores`.`datos_generales`.`segundo_apellido` AS `segundo_apellido`,`info_colaboradores`.`datos_generales`.`apellido_casada` AS `apellido_casada`,`info_colaboradores`.`datos_generales`.`dpi` AS `dpi`,`info_colaboradores`.`datos_generales`.`pasaporte` AS `pasaporte`,`info_colaboradores`.`datos_generales`.`fecha_nacimiento` AS `fecha_nacimiento`,`info_colaboradores`.`datos_generales`.`direccion` AS `direccion`,`info_colaboradores`.`datos_generales`.`departamento_direccion` AS `departamento_direccion`,`info_colaboradores`.`datos_generales`.`municipio_direccion` AS `municipio_direccion`,`info_colaboradores`.`datos_generales`.`telefono` AS `telefono`,`info_colaboradores`.`datos_generales`.`celular` AS `celular`,`info_colaboradores`.`datos_generales`.`email_personal` AS `email_personal`,`info_colaboradores`.`datos_generales`.`email_institucional` AS `email_institucional`,`info_colaboradores`.`datos_generales`.`observacion` AS `observacion`,`info_colaboradores`.`datos_generales`.`profesion` AS `profesion`,concat(`info_colaboradores`.`datos_generales`.`primer_nombre`,\' \',`info_colaboradores`.`datos_generales`.`segundo_nombre`,\' \',`info_colaboradores`.`datos_generales`.`tercer_nombre`,\' \',`info_colaboradores`.`datos_generales`.`primer_apellido`,\' \',`info_colaboradores`.`datos_generales`.`segundo_apellido`,\' \',`info_colaboradores`.`datos_generales`.`apellido_casada`) AS `Nombre_Completo` from `info_colaboradores`.`datos_generales` where (`info_colaboradores`.`datos_generales`.`cif` = 12947)
md5=7cee94c54655bae0bce5855b02885012
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2015-12-30 09:23:45
create-version=1
source=select `datos_generales`.`cif` AS `cif`,`datos_generales`.`sexo` AS `sexo`,`datos_generales`.`estado_civil` AS `estado_civil`,`datos_generales`.`nit` AS `nit`,`datos_generales`.`nacionalidad` AS `nacionalidad`,`datos_generales`.`primer_nombre` AS `primer_nombre`,`datos_generales`.`segundo_nombre` AS `segundo_nombre`,`datos_generales`.`tercer_nombre` AS `tercer_nombre`,`datos_generales`.`primer_apellido` AS `primer_apellido`,`datos_generales`.`segundo_apellido` AS `segundo_apellido`,`datos_generales`.`apellido_casada` AS `apellido_casada`,`datos_generales`.`dpi` AS `dpi`,`datos_generales`.`pasaporte` AS `pasaporte`,`datos_generales`.`fecha_nacimiento` AS `fecha_nacimiento`,`datos_generales`.`direccion` AS `direccion`,`datos_generales`.`departamento_direccion` AS `departamento_direccion`,`datos_generales`.`municipio_direccion` AS `municipio_direccion`,`datos_generales`.`telefono` AS `telefono`,`datos_generales`.`celular` AS `celular`,`datos_generales`.`email_personal` AS `email_personal`,`datos_generales`.`email_institucional` AS `email_institucional`,`datos_generales`.`observacion` AS `observacion`,`datos_generales`.`profesion` AS `profesion`,concat(`datos_generales`.`primer_nombre`,\' \',`datos_generales`.`segundo_nombre`,\' \',`datos_generales`.`tercer_nombre`,\' \',`datos_generales`.`primer_apellido`,\' \',`datos_generales`.`segundo_apellido`,\' \',`datos_generales`.`apellido_casada`) AS `Nombre_Completo` from `datos_generales` where (`datos_generales`.`cif` = 12947)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select `info_colaboradores`.`datos_generales`.`cif` AS `cif`,`info_colaboradores`.`datos_generales`.`sexo` AS `sexo`,`info_colaboradores`.`datos_generales`.`estado_civil` AS `estado_civil`,`info_colaboradores`.`datos_generales`.`nit` AS `nit`,`info_colaboradores`.`datos_generales`.`nacionalidad` AS `nacionalidad`,`info_colaboradores`.`datos_generales`.`primer_nombre` AS `primer_nombre`,`info_colaboradores`.`datos_generales`.`segundo_nombre` AS `segundo_nombre`,`info_colaboradores`.`datos_generales`.`tercer_nombre` AS `tercer_nombre`,`info_colaboradores`.`datos_generales`.`primer_apellido` AS `primer_apellido`,`info_colaboradores`.`datos_generales`.`segundo_apellido` AS `segundo_apellido`,`info_colaboradores`.`datos_generales`.`apellido_casada` AS `apellido_casada`,`info_colaboradores`.`datos_generales`.`dpi` AS `dpi`,`info_colaboradores`.`datos_generales`.`pasaporte` AS `pasaporte`,`info_colaboradores`.`datos_generales`.`fecha_nacimiento` AS `fecha_nacimiento`,`info_colaboradores`.`datos_generales`.`direccion` AS `direccion`,`info_colaboradores`.`datos_generales`.`departamento_direccion` AS `departamento_direccion`,`info_colaboradores`.`datos_generales`.`municipio_direccion` AS `municipio_direccion`,`info_colaboradores`.`datos_generales`.`telefono` AS `telefono`,`info_colaboradores`.`datos_generales`.`celular` AS `celular`,`info_colaboradores`.`datos_generales`.`email_personal` AS `email_personal`,`info_colaboradores`.`datos_generales`.`email_institucional` AS `email_institucional`,`info_colaboradores`.`datos_generales`.`observacion` AS `observacion`,`info_colaboradores`.`datos_generales`.`profesion` AS `profesion`,concat(`info_colaboradores`.`datos_generales`.`primer_nombre`,\' \',`info_colaboradores`.`datos_generales`.`segundo_nombre`,\' \',`info_colaboradores`.`datos_generales`.`tercer_nombre`,\' \',`info_colaboradores`.`datos_generales`.`primer_apellido`,\' \',`info_colaboradores`.`datos_generales`.`segundo_apellido`,\' \',`info_colaboradores`.`datos_generales`.`apellido_casada`) AS `Nombre_Completo` from `info_colaboradores`.`datos_generales` where (`info_colaboradores`.`datos_generales`.`cif` = 12947)
