<?php

echo 'ASOCIACIÓN PARA EL
CRECIMIENTO EDUCATIVO
REG. COOPERATIVO Y APOYO
TURÍSTICO DE ESQUIPULAS
-ACERCATEKILOMETRO
226.5 CARRETERA DE
ASFALTADA HACIA
FRONTERA DE HONDURAS
PARQUE CHATUN
ESQUIPULAS, CHIQUIMULA
N.I.T. 9206609-7
------------------------------------------
RESOLUCION DE SISTEMA
2016-1-27-491
RESOLUCION DE FACTURAS DEL
31-12-1969
DE LA A LA
FACTURA SERIE NO.
***************************************
27-10-2016 16:18:36
Computadora No. 1
Transacción F_581151a5eb3c5
N.I.T.:
NOMBRE: C/F
DIRECCION: ---
------------------------------------------
CA PROD P/U TOTAL
TOTAL Q. 0.00
TIPO PAGO:
CAMBIO Q.:
# ORDEN
SUJETO A PAGOS TRIMESTRALES
ESPERAMOS QUE VUELVA PRONTO
GRACIAS POR PREFERIRNOS';

?>